bool_names = "var_front_door_open,var_front_door_locked,var_darkness_arrived,var_gun_was_shot,var_cabinet_moved,var_kitchen_open,var_kitchen_water_running,var_joe_dead,var_picture_loose,var_bathroom_water_running,var_trunk_unlocked,var_daisy_dead,var_rug_on_fire,first_launch,show_image,blank_image,did_show_splashscreen,did_start_game,did_prompt_replay"

--object properties
dict_name = 1
descr = 2
room_num = 3
pic_num = 4
draw_pos = 5
temp_num = 6

--game conditions
var_front_door_open 	= false
var_front_door_locked = false
var_match_duration = 0 --var 3
var_turn_count = 0
var_darkness_arrived = false --var 16
var_gun_was_shot = false
var_cabinet_moved = false
var_kitchen_open = false
var_kitchen_water_running = false
var_joe_dead = false
var_picture_loose = false
var_bathroom_water_running = false
var_trunk_unlocked = false
var_daisy_dead = false --var 11
var_rug_on_fire = false --var 5

--pic numbering generated by packer
pic_frontyard = 1
pic_front_door_closed = 2
pic_front_door_open = 3
pic_entryhall_crowded = 4
pic_entryhall_closed = 5
pic_entryhall_open = 6
pic_forest = 7
pic_jewel_note = 8
pic_math_note = 9
pic_taunt_note = 10
pic_basement_note = 11
pic_kitchen_closed = 12
pic_kitchen_open = 13
pic_cabinet_closed = 14
pic_cabinet_open = 15
pic_cabinet_interior = 16
pic_fridge_closed = 17
pic_fridge_open = 18
pic_fridge_interior = 19
pic_kitchen_bricks = 20
pic_kitchen_hole = 21
pic_sink_interior = 22
pic_tree = 23
pic_library_closed = 24
pic_library_open = 25
pic_at_stairway = 26
pic_attic = 27
pic_backyard_house_closed = 28
pic_backyard_house_open = 29
pic_backyard_fence_closed = 30
pic_backyard_fence_open = 31
pic_basement = 32
pic_bathroom = 33
pic_boys_bedroom = 34
pic_cemetary_closed = 35
pic_cemetary_open = 36
pic_gravedigger = 37
pic_chest_interior = 38
pic_crawlspace = 39
pic_dining_room_closed = 40
pic_dining_room_open = 41
pic_dining_room_fire = 42
pic_dining_room_hole = 43
pic_doorway = 44
pic_gun = 45
pic_hole_interior = 46
pic_junction = 47
pic_large_bedroom = 48
pic_large_bedroom_dagger_lines = 49
pic_nursery = 50
pic_on_stairway = 51
pic_pantry = 52
pic_passageway = 53
pic_sideyard_open = 54
pic_sideyard_closed = 55
pic_small_bedroom = 56
pic_storage_room = 57
pic_study_closed = 58
pic_study_open = 59
pic_tower = 60
pic_trapdoor = 61
pic_treetop = 62
pic_tunnel = 63
pic_trapdoor_open = 64

--spr numbering is manual
spr_male = 65
spr_female = 66
spr_entryhall_doorway = 67
spr_welcome_mat = 68
spr_note = 69
spr_candle = 70
spr_pitcher = 71
spr_matches = 72
spr_butterknife = 73
spr_small_key = 74
spr_sam_dead = 75
spr_joe_dots = 76
spr_joe_xs = 77
spr_dagger = 78
spr_towel = 79
spr_brick = 80
spr_jewels = 81
spr_trapdoor_closed = 82
spr_picture = 83
spr_button = 84
spr_trunk_closed = 85
spr_trunk_open = 86
spr_skeleton_key = 87
spr_sledgehammer = 88
spr_daisy_dots = 89
spr_daisy_xs = 90
spr_shovel = 91

--x,y,w,h,layer
sprites = {{113,5,15,27,3},
{97,5,15,27,3},
{0,29,27,3,3},
{20,20,31,12,2},
{83,1,19,9,2}, --note
{100,19,20,13,4},
{105,15,23,17,1},
{0,21,19,11,2},
{122,7,6,25,4},
{39,19,28,13,1},--small_key
{83,11,45,21,2},
{94,2,5,1,3},
{101,0,10,5,3},
{103,0,24,15,1},
{0,22,12,10,1},
{23,24,15,8,1},--brick
{0,24,15,8,4},
{86,24,16,8,1},
{62,0,29,16,3},
{41,29,4,3,3}, --button
{33,18,30,14,4},
{66,18,31,14,4},
{102,0,26,11,2},
{55,18,27,14,2},
{112,0,4,2,3},
{119,0,9,4,3},
{109,0,11,19,4}}